# Site setings
name: "Tony Klapatch"
description: "Web developer with a passion for local municipal planning & volunteering based in Easton, PA."
meta_description: "Web developer with a passion for local municipal planning & volunteering based in Easton, PA."
#logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://tonyklapatch.me/
disqus: "tonyklapatch"
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
cover_image: bc_1.jpg
# Add your GA Tracking Id
#ga_analytics:

# Author
author:
  name: "Tony Klapatch"
  image: "authorimage.jpg"
  greetings: "Tony Klapatch"
  description: "Web developer with a passion for local municipal planning & volunteering based in Easton, PA."
  bio: "Web developer with a passion for local municipal planning & volunteering based in Easton, PA."

# Contact form setings
email: tony@klapatch.net
#contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
#thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
#twitter: "username"
facebook: "TonyKlapatch"
github: "tonyklapatch"
#codepen: "username"
#dribbble: "username"
#medium: "@username"
instagram: "tklapatch"
#pinterest: "username"
linkedin: "anthonyklapatch"
#producthunt: "@username"

# Navigation
navigation:
  - text: About
    url: /about
  - text: Archive
    url: /tags

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
